config/routes.rb
Zackapack::Application.routes.draw do
 

  
root :to => 'pages#home'

  match '/about' => 'pages#about'
  match '/contact' => 'pages#contact'
  match '/one' => 'lessons#one'
  match '/two' => 'lessons#two'
  match '/three' => 'lessons#three'
  
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def one
  end

  def two
  end

  def three
  end

  def four
  end

  def five
  end

  def six
  end

  def seven
  end

  def eight
  end

  def nine
  end

  def ten
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Zackapack.com</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Contact Us", contact_path %></li>
          
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zackapack.com</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/lessons/eight.html.erb
<h1>Lessons#eight</h1>
<p>Find me in app/views/lessons/eight.html.erb</p>

app/views/lessons/five.html.erb
<h1>Lessons#five</h1>
<p>Find me in app/views/lessons/five.html.erb</p>

app/views/lessons/four.html.erb
<h1>Lessons#four</h1>
<p>Find me in app/views/lessons/four.html.erb</p>

app/views/lessons/nine.html.erb
<h1>Lessons#nine</h1>
<p>Find me in app/views/lessons/nine.html.erb</p>

app/views/lessons/one.html.erb
<h3>Lesson 1: A Basic HTML Web Page</h3>
<%= image_tag("14.gif") %>

<p>
Let's get started! Turn on your computer. We're going to start by creating a new folder where all our files will live. Right click on the Desktop. Click on  "New" and select "Folder". Change the name from "New folder" to "Zackapack" and hit the "Enter" key on your keyboard.
</p>
1. <%= image_tag("one/newfolder.png")%> 2.<%= image_tag("one/zackname.png")%>
<p>
Alright! Now we're set up. Let's start coding!! We code with a text editor. Let's use Notepad since it's free and already on your computer ;) Notepad is usually hard to find but if you follow this path you should find it:
</p>
<p>
Start Menu > All Programs > Accessories > Notepad
</p>
<p>
Did you find it? Okay, let's code! Every webpage opens with the html tag and ends with it's closing tag:
</p>
<%=image_tag("one/html1.png")%>
<p>
The next line of code we need to add is the head. The head opens and closes just like the html tag. The head is important because it often holds lots of important stuff that makes your webpage awesome! Let's add that now:
</p>
<%= image_tag("one/head.png")%>
<p>
Inside the open and closed head tags lives the title. The title shows up right above the webpage and tells people the name of the page they are on. Let's add a title and call it "Home" because this webpage is going to be the home page for our future website:
</p>
<%= image_tag("one/title.png")%>
<p>
Whew! That was a lot of work. But don't stop now! Next we're going to leave the head and work on the body of the webpage. This is the best part! Add the open and closed body tags like so:
</p>
<%= image_tag("one/body.png")%>
<p>
This is where all our content for our webpage lives. Let's add some now! We'll start by adding a header tag. A header is like a title for your body. They come in different sizes (h1, h2, h3, h4...etc.). Strangely h1 is the largest size. Let's add one called "Zack's Home Page":
</p>
<%= image_tag("one/header.png")%>
<p>
Okay, and now for our last part of coding! I promise :) Let's add a paragraph tag to this page. Paragraph tags usually hold text and are abbreviated with a "p". Let's add one with the text "Luke, I am your father!":
</p>
<%=image_tag("one/paragraph.png")%> 
<p>
Okay now it's time to save this awesome webpage! In Notepad click "File" and then select "Save as". When the "Save as" screen appears you need to change three things to save it correctly in the right place. 
<p>
1. You need to change where it is going to be saved. Click "Desktop" and then select your folder you created at the beginning of this tutorial ("Zackapack"). 
</p>
1.<%=image_tag("one/saveas1.png")%> 2.<%=image_tag("one/saveas2.png")%> 
<p>
2. Next we need to give the file a name. We'll call it "index.html" because this is going to be the home page of our future website. 
</p>
<%=image_tag("one/saveas3.png")%>
<p> 
3. Lastly we need to change the "Save as type" to "All Files" instead of "Text Documents(*.txt)". Then we click "Save". 
</p>
<%=image_tag("one/saveas4.png")%>
<p>
Now lets see this webpage in action! Open up a web browser, click on "File " and select "Open" (You can also do this by clicking  the control key and the o key at the same time [ctrl+o] ). Next select your folder from the Desktop ("Zackapack") and open "index.html".
</p>
1.<%=image_tag("one/open1.png")%> 2.<%=image_tag("one/open2.png")%>
<p>
...and you should see...
</p>
<%=image_tag("one/webpage.png")%>
<p>
Congratulations! You just created a webpage. You are learning fast young Skywalker. Here is a fun activity to practice your skills:
</br>
Create a new webpage just like you did in this tutorial but this time call it "darthvader.html". Save it in your Zackapack folder. Try giving it a header with a cool name and a different size this time. Also add a paragraph that talks about Darth Vader and his evil ways. <%= link_to "Email me", contact_path %> and let me know how it goes!
</p>




 

app/views/lessons/seven.html.erb
<h1>Lessons#seven</h1>
<p>Find me in app/views/lessons/seven.html.erb</p>

app/views/lessons/six.html.erb
<h1>Lessons#six</h1>
<p>Find me in app/views/lessons/six.html.erb</p>

app/views/lessons/ten.html.erb
<h1>Lessons#ten</h1>
<p>Find me in app/views/lessons/ten.html.erb</p>

app/views/lessons/three.html.erb
<h3>Lesson 3: All Kinds of Lists</h3>
<%= image_tag("55.gif")%>
<p>Coming soon to a computer near you..</p>

app/views/lessons/two.html.erb
<h3>Lesson 2: Adding an Awesome Image to your Page</h3>
<%= image_tag("56.gif")%>

<p>Coming soon to a computer near you..</p>

app/views/pages/about.html.erb
<h3>About us:</h3>
<p>This is Zack's website. It was created to make him a Jedi master of html. We hope you enjoy the awesome images and html tutorials :)</p>
<%= image_tag("7.gif") %>

app/views/pages/contact.html.erb
<h3>Have any questions? Comments? <a href="mailto:dansbeerlist@gmail.com">Email us</a>!</h3>
<%= image_tag("30.gif") %>

app/views/pages/home.html.erb
<%= image_tag("18.gif") %><%= image_tag("15.gif") %>
</br>
<%= image_tag("waving.gif") %><%= image_tag("voice.png")%>
</br>
<ul>
  <li><%= link_to "Lesson1", one_path %></li>
  <li><%= link_to "Lesson2", two_path %></li>
  <li><%= link_to "Lesson3", three_path %></li>
</ul>